-- Create tweets table (if not exists)
create table if not exists tweets (
  id bigint primary key,
  text text,
  user_info jsonb,
  url text,
  created_at timestamp with time zone,
  collected_at timestamp with time zone default timezone('utc'::text, now()) not null,
  risk_score float,
  risk_analysis jsonb
);

-- System Logs Table for Frontend Visibility
create table if not exists system_logs (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  level text default 'INFO',
  message text
);

-- System Commands Table for Frontend Control
create table if not exists system_commands (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  command text not null,
  status text default 'PENDING', -- 'PENDING', 'PROCESSING', 'COMPLETED', 'FAILED'
  processed_at timestamp with time zone
);

-- Enable Row Level Security (RLS) if you want to restrict access
-- For this free tool, we might keep it open or just enabled for anon
alter table tweets enable row level security;
alter table system_logs enable row level security;
alter table system_commands enable row level security;

-- Policies (Simplified for development/demo)
create policy "Enable all access for all users" on tweets for all using (true) with check (true);
create policy "Enable all access for all users" on system_logs for all using (true) with check (true);
create policy "Enable all access for all users" on system_commands for all using (true) with check (true);
