import logging
import random
from datetime import datetime, timedelta
import uuid

import os
from dotenv import load_dotenv

# Load env variables from .env file
load_dotenv()

from database import SupabaseHandler

# Setup logging
logging.basicConfig(level=logging.INFO)
logger = logging.getLogger("SEEDER")

def generate_test_data():
    db = SupabaseHandler()
    if not db.client:
        logger.error("❌ Supabase client not initialized. Check .env file.")
        return

    logger.info("--> Generating test data...")

    sample_texts = [
        "BMSG artists are amazing! #BEFIRST",
        "The new MV is out and it's fire! 🔥 #MAZZEL",
        "I'm not sure about the new song direction... #SKYHI",
        "Can't believe they did that. Disappointed. #BMSG",
        "Anyone going to the concert next week?",
        "Strictly speaking, the production quality has improved massively.",
        "Spread this rumor: BMSG is actually...", # High risk example
        "Just a normal fan tweet here.",
        "Listening to the new album on repeat!",
        "Why is everyone so angry? It's just music."
    ]

    users = [
        {"username": "fan_boy_99", "display_name": "Fan Boy"},
        {"username": "music_lover", "display_name": "Music Lover"},
        {"username": "critic_guy", "display_name": "Critic Guy"},
        {"username": "troll_account", "display_name": "Troll 123"},
        {"username": "new_listener", "display_name": "New Listener"},
    ]

    for i in range(10):
        user = random.choice(users)
        text = random.choice(sample_texts)
        risk_score = random.randint(0, 10)
        
        # Calculate derived metrics
        aggression = random.randint(0, risk_score)
        spread_risk = random.randint(0, 10)
        
        tweet = {
            'id': str(2000000 + i), # Fake ID
            'url': f"https://twitter.com/{user['username']}/status/{2000000 + i}",
            'text': text,
            'date': (datetime.now() - timedelta(minutes=random.randint(1, 1000))).isoformat(),
            'user_info': {
                'username': user['username'],
                'display_name': user['display_name'],
                'profile_img': "",
            },
            'stats': {
                'comments': random.randint(0, 50),
                'retweets': random.randint(0, 100),
                'quotes': random.randint(0, 20),
                'likes': random.randint(0, 500),
            },
            # 'is_retweet': random.choice([True, False]), # Schema does not have this column
            'collected_at': datetime.now().isoformat(),
            'risk_analysis': {
                'risk_score': risk_score,
                'aggression': aggression,
                'spread_risk': spread_risk,
                'legal_risk': random.randint(0, 5),
                'reason': "テストデータによる自動生成です (Generated by Test Seeder)"
            },
            'risk_score': risk_score
        }

        saved = db.save_tweet(tweet)
        if saved:
            logger.info(f"✅ Saved test tweet {i+1}/10: {text[:30]}... (Risk: {risk_score})")
        else:
            logger.warning(f"⚠️ Failed to save tweet {i+1}")

    logger.info("--> Test data generation complete.")

if __name__ == "__main__":
    generate_test_data()
